package com.yahoo.ycsb.generator;

public abstract class FloatGenerator extends Generator {
    float lastfloat;

    /**
     * Set the last value generated. FloatGenerator subclasses must use this
     * call to properly set the last string value, or the lastString() and
     * lastFloat() calls won't work.
     */
    protected void setLastFloat(float last) {
        lastfloat = last;
    }

    /**
     * Return the next value as a float. When overriding this method, be sure to
     * call setLastString() properly, or the lastString() call won't work.
     */
    public abstract float nextFloat();

    /**
     * Generate the next string in the distribution.
     */
    public String nextString() {
        return "" + nextFloat();
    }

    /**
     * Return the previous string generated by the distribution; e.g., returned
     * from the last nextString() call. Calling lastString() should not advance
     * the distribution or have any side effects. If nextString() has not yet
     * been called, lastString() should return something reasonable.
     */
    @Override
    public String lastString() {
        return "" + lastFloat();
    }

    /**
     * Return the previous float generated by the distribution. This call is
     * unique to FloatGenerator subclasses, and assumes FloatGenerator
     * subclasses always return floats for nextFloat() (e.g. not arbitrary
     * strings).
     */
    public float lastFloat() {
        return lastfloat;
    }

    /**
     * Return the expected value (mean) of the values this generator will
     * return.
     */
    public abstract double mean();
}
